namespace customTiles_ChemicalPlant {
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const transparency16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile1 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile2 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile17 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile19 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile20 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile16 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile24 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile25 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile26 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile29 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile30 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile53 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile58 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile60 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile7 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile18 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile21 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile27 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile31 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile63 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile61 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile3 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile4 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile5 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile6 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile8 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile9 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile10 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile11 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile12 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile13 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile14 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile15 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile22 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile23 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile28 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile32 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile33 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile34 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile35 = image.ofBuffer(hex``);
    //% fixedInstance jres blockIdentity=images._tile
    //% tags="tile category-ChemicalPlant"
    export const tile36 = image.ofBuffer(hex``);
}
